### ISSUE TITLE
lgi.GLib.String('') does not work: bad argument #1 to 'pairs' (table expected, got string)

### ISSUE THREAD

**Issue by blueyed** [pavouk/lgi#100]
> lgi = require('lgi')
> s = lgi.GLib.String('')
/usr/share/lua/5.2/lgi/record.lua:123: bad argument #1 to 'pairs' (table expected, got string)
stack traceback:
	[C]: in function 'pairs'
	/usr/share/lua/5.2/lgi/record.lua:123: in function </usr/share/lua/5.2/lgi/record.lua:108>
	(...tail calls...)
	stdin:1: in main chunk
	[C]: in ?

Just `s = lgi.GLib.String()` works, as does `s = lgi.GLib.String({})`.

It appears to be used like this in the tests: https://github.com/pavouk/lgi/blob/master/tests/dbus.lua#L102

My intention is to use https://developer.gnome.org/glib/stable/glib-Strings.html#g-string-hash in awesomeWM's lua interface.

**Comment by blueyed** [comment]
This appears to work:

    lgi.GLib.String():append("foo"):hash()

**Comment by pavouk** [comment]
I'm not able to reproduce.  Your transcript looks like lgi was not able to associate g_string_new() with Glib.String class as an constructor, so default record/struct constructor will kick in (and this is the one which hates string constant as an argument).

What version of lgi are you using?  Do you have the locale (LC_ALL) set to something non-english?  If yes, are you able to reproduce even after setting LC_ALL=en_US.UTF8?  If this is the case, would lgi 'master' help - recently a fix for turkish locale went in, and this one could also be related to this problem.

**Comment by blueyed** [comment]
I've been using lua-lgi:amd64 0.7.2-1 (Ubuntu Trusty).

After upgrading it this issue appears to be solved:

> The following packages will be upgraded:
   libglib2.0-0 [2.40.2-0ubuntu1 -> 2.42.0-2]  libglib2.0-0:i386 [2.40.2-0ubuntu1 -> 2.42.0-2] libglib2.0-bin [2.40.2-0ubuntu1 -> 2.42.0-2]  libglib2.0-dev [2.40.2-0ubuntu1 -> 2.42.0-2] lua-lgi [0.7.2-1 -> 0.8.0-2]
