### ISSUE TITLE
GtkSourceView integration with LGI

### ISSUE THREAD

**Issue by FelipeFS** [pavouk/lgi#101]
So, I believe **GtkSourceView** is not a true class on Gtk+ 3. If you look at the documentation, you will not find **GtkSourceViewClass**. The same goes for its associated objects (gutter, gutter renderer, source buffer). Thus, if you pass a GtkSourceView to LGI, you will grab a **GtkTextView**, and will not have access to the methods of GtkSourceView. The same goes to its associates. Luckily, looks like most of the methods for GtkSourceView and its associates receives simple types (integers, strings, booleans).

So... If there is no objection and nobody is assigned to the task to integrate GtkSourceView, I would like to assign myself. I would need a start point, though, to know were and how I could create a *false* class for those objects.

**Comment by pavouk** [comment]
Of course, there is no objection against any kind of work anyone wants to do, quite the opposite is true.  However, I must confess I don't trully understand whats the problem with current GtkSourceView support.  At least samples/console.lua and samples/gtk-demo/main.lua use GtkSourceView just fine without any problems.  If you can provide short sample reproducing the problem, I might be able to try to help to solve it.

**Comment by FelipeFS** [comment]
Oh, you can use the widget, but as TextView. If I pass the pointer of a GtkSourceView to my Lua function:
```
function lua_function(sourceview_lightuserdata)
  local widget = Gtk.Widget(sourceview_lightuserdata)
  print(tostring(widget))
  widget:set_auto_indent(false)
end
```


The print will report ```lgi.obj 0x8d7f1e8:Gtk.TextView(GtkSourceView)```. The LGI will treat it as GtkTextView, the closest class to GtkSourceView. Now, if you try to use a GtkSourceView function, as ```gtk_source_view_set_auto_indent()```, your call to that ```lua_function``` will fail.

**Comment by pavouk** [comment]
I think the problem here is that GtkSourceView package metadat is not loaded at all, tehrefore lgi associates incoming class with with its closest ancestor. Try adding
```lua
local GtkSourceView = lgi.GtkSourceView
```
somewhere before you try to get lgi object from lightuserdata and I guess that it will work.

**Comment by FelipeFS** [comment]
Don't work:
```
PANIC: unprotected error in call to Lua API (/usr/share/lua/5.2/lgi/namespace.lua:151: Typelib file for namespace 'GtkSourceView' (any version) not found)
```

**Comment by pavouk** [comment]
Oops, I'm sorry about incorrect advice.  The package for GtkSourceView is named GtkSource (somewhat inconsistently), so you need to do 

```lua
local GtkSource = lgi.GtkSource
```

as is done e.g. in samples/console.lua in lgi distribution.

**Comment by pavouk** [comment]
If it will choke again that even GtkSource package cannot be loaded, then you have to install typelib for GtkSource; on my system it lives in  /usr/lib64/girepository-1.0/GtkSource-3.0.typelib

**Comment by FelipeFS** [comment]
Thank you very much! Worked!
