### ISSUE TITLE
Test gobject.ctor_gc() (seems to?) hang with lua 5.1.5

### ISSUE THREAD

**Issue by psychon** [pavouk/lgi#103]
Hi,

I'm on debian testing, I am using lua 5.1.5 and the `gobject.ctor_gc()` test seems to hang for me. Looking at the code, this test is already disabled for lua 5.3 for similar reasons.

If I change

    if rawget(_G, '_VERSION') ~= 'Lua 5.3' then  

to

    if rawget(_G, '_VERSION') == 'Lua 5.2' then

Then the test suite finishes. (I guess that it will also finish if I give it enough time, but that's not really the idea of this test...)

**Comment by pavouk** [comment]
Hopefully fixed by commit above.  Feel free to reopen if the problem persists.
