### ISSUE TITLE
Can there be a new release?

### ISSUE THREAD

**Issue by gregier** [pavouk/lgi#104]
It would be great if there could be a new release to coincide with GNOME 3.16.

At least libpeas and users of the Lua backend would benefit.

Thanks!

**Comment by craigbarnes** [comment]
:+1:

**Comment by gregier** [comment]
Any news on this issue? The release is today and I would love to require a specific version of LGI.

**Comment by pavouk** [comment]
I was hoping to release it during the weekend, but failed to find the time again.  The main thing I would to solve is remaining bug with Lua 5.3 (in)compatibility.  I guess that I'll punt on this one for the time being and release tonight the actual master.  Lua5.3 compatibility can then come later as dot-release fix.

**Comment by pavouk** [comment]
0.9.0 was released, uploaded to luarocks. I'll release 0.9.1 whenever I get to fixing at least Lua 5.3 compatibility, ideally even more of pending issues.
