### ISSUE TITLE
undefined symbol: lua_gettop

### ISSUE THREAD

**Issue by AdamMZ** [pavouk/lgi#110]
I'm using this IDE: http://eclipse.org/koneki/ldt/
I typed down just "require 'lgi'" to see if it works or not, and I found this error:

Exception in thread "main" com.naef.jnlua.LuaRuntimeException: error loading module 'lgi.corelgilua51' from file '/usr/local/lib/lua/5.1/lgi/corelgilua51.so':
	/usr/local/lib/lua/5.1/lgi/corelgilua51.so: undefined symbol: lua_gettop
	at com.naef.jnlua.LuaState.lua_pcall(Native Method)
	at com.naef.jnlua.LuaState.call(LuaState.java:555)
	at org.eclipse.koneki.ldt.support.lua51.internal.interpreter.JNLua51Launcher.run(JNLua51Launcher.java:128)
	at org.eclipse.koneki.ldt.support.lua51.internal.interpreter.JNLua51Launcher.main(JNLua51Launcher.java:143)

The IDE has its own interpreter but I've set up a local interpreter. And I think that's it. Help please.

**Comment by ff2000** [comment]
Most likely you used a different lua version to compile lgi than you run your code with.
I saw a similar issue here on Gentoo. lgi was compiled with lua5.2 but run with lua5.1.

AdamMZ wrote:

**Comment by AdamMZ** [comment]
I'm using 5.1 to compile it.

**Comment by AdamMZ** [comment]
I used Lua 5.1 to compile those.

**Comment by ff2000** [comment]
What does this give you:
```
ldd /usr/local/lib/lua/5.1/lgi/corelgilua51.so | grep lua
```

Adam Zaim wrote:

**Comment by pavouk** [comment]
I'm 100% sure that the problem is caused by running lgi against different Lua version than against the one lgi was compiled, so this is really installation/environment-setup issue and not lgi issue per se.

**Comment by chidea** [comment]
When there is liblua.so missing when you executed `ldd corelgilua51.so | grep lua`, it means your lgi was built without linking one. This is default behaviour on linux systems by Makefile.
This can be resolved by forcing liblua.so file to be linked.
`lgi/Makefile` has to be edited like below.
```
else
CORE = corelgilua51.so                                                                                                                LIBFLAG = -shared                                                                                                                     CCSHARED = -fPIC
LIBS += $(shell $(PKG_CONFIG) --libs lua)                                                                                            endif 
```
