### ISSUE TITLE
Can't find pango_color_parse

### ISSUE THREAD

**Issue by silverhammermba** [pavouk/lgi#114]
I'm try to call [pango_color_parse](https://developer.gnome.org/pango/stable/pango-Text-Attributes.html#pango-color-parse) on Arch Linux using lgi 0.9

    $ lua -e 'print(require("lgi").Pango.color_parse)'
    nil

Why doesn't this work? The function is even declared in the same header as `pango_parse_markup` which works fine:

    $ lua -e 'print(require("lgi").Pango.parse_markup)'
    lgi.fun(0x7fb097f06b10): Pango.parse_markup

**Comment by pavouk** [comment]
pango_color_parse looks like ordinary method of class/struct Pango.Color, so I guess that `print(require('lgi').Pango.Color.parse)` will work.

**Comment by silverhammermba** [comment]
Thanks, that worked for me!
