### ISSUE TITLE
Uninitialized integer variable with g_data_input_stream_read_line_finish

### ISSUE THREAD

**Issue by psychon** [pavouk/lgi#118]
Hi,

consider the following C program (which has many leaks and I should feel bad for writing it):
```C
#include <gio/gunixinputstream.h>
#include <stdio.h>

static GMainLoop *loop;

static void callback(GObject *obj, GAsyncResult *res, gpointer unused)
{
	gsize length;
	gchar *line;
	GError *error = NULL;
	line = g_data_input_stream_read_line_finish(G_DATA_INPUT_STREAM(obj), res, &length, &error);
	printf("'%s' %d %s\n", line, (int) length, error ? error->message : "no error");
	g_main_loop_quit(loop);
}

int main()
{
	g_type_init();
	GInputStream *s1 = g_unix_input_stream_new(0, FALSE);
	GDataInputStream *s2 = g_data_input_stream_new(G_INPUT_STREAM(s1));
	g_data_input_stream_read_line_async(s2, G_PRIORITY_DEFAULT, NULL, callback, NULL);
	loop = g_main_loop_new(NULL, FALSE);
	g_main_loop_run(loop);
	return 0;
}
```
And call it as `./a.out < /dev/null`. The output is (for me) `'(null)' 38639168 no error`.

If we change the callback function to have `gsize length = 0;`, the output becomes `'(null)' 0 no error`. I think that this shows that `g_data_input_stream_read_line_finish` ignores the `length` argument in case of end-of-file.

Now the same in lua:

```lua
$ lua -e 'lgi = require("lgi")
Gio, GLib = lgi.Gio, lgi.GLib
Gio.DataInputStream.new(Gio.UnixInputStream.new(0, false)):read_line_async(GLib.PRIORITY_DEFAULT, nil, function(obj, res) 
    local a, b, c = obj:read_line_finish(res)
    print(type(a), a, type(b), b, type(c), c)
end)
GLib.MainLoop.new(nil, false):run()' < /dev/null                                   
string		number	1.4073105040022e+14	nil	nil
^C^C
```
Alternatively (and this time with another number, showing that this is not really deterministic):
```lua
$ lua -e 'lgi = require("lgi")
Gio, GLib = lgi.Gio, lgi.GLib
Gio.Async.call(function() print(Gio.DataInputStream.new(Gio.UnixInputStream.new(0, false)):async_read_line()) end)()'  < /dev/null 
	1.4072912952838e+14
```

Here the `NULL` return value is transformed in an empty string and the length is just some random large number. Thus, I cannot easily detect the end-of-file condition, because empty lines look the same. Checking if `#a == b` might work reliably, but seems like a bad hack to me.

My feeling says that lgi should initialize this number to zero before calling the function that supposedly fills it ([out] annotation), but I am not completely sure.

Looking forward to your ideas. :-)

**Comment by pavouk** [comment]
From the description this looks like a bug in g_data_input_stream_read_line_finish(); the documentation clearly states that the argument is output-only and the annotation suggests the same, which means that input value to the function really should not matter at all.\

Interesting thing is that I'm not able to reproduce using your samples:
```
$ lua -e 'lgi = require("lgi")
Gio, GLib = lgi.Gio, lgi.GLib
Gio.DataInputStream.new(Gio.UnixInputStream.new(0, false)):read_line_async(GLib.PRIORITY_DEFAULT, nil, function(obj, res) 
    local a, b, c = obj:read_line_finish(res)
    print(type(a), a, type(b), b, type(c), c)
end)
GLib.MainLoop.new(nil, false):run()' < /dev/null 
string		number	1.0	nil	nil
```

```
$  lua -e 'lgi = require("lgi")
Gio, GLib = lgi.Gio, lgi.GLib
Gio.Async.call(function() print(Gio.DataInputStream.new(Gio.UnixInputStream.new(0, false)):async_read_line()) end)()'  < /dev/null 
	0.0
```

I have Fedora-22, which has glib-1.2.10.  Could it be that fix went into glib and you have older glib with the bug?

**Comment by pavouk** [comment]
Scratch that, I can reproduce, it is not dependent on glib.  I had checked out an experimental branch with some marshalling improvements, which accidentally fixed the problem (or more correctly worked around the bug in glib).

I'm looking into writing the fix for main.

**Comment by pavouk** [comment]
Fix pushed to master.  Thanks for precise report and sorry about my latency.

**Comment by psychon** [comment]
Uhm. This fix now actually reached me and now I wonder how to detect the end-of-file condition. In the C API this is done because the function returns `NULL`. On the Lua side, lgi turns this into an empty string and now I cannot tell apart end-of-file and an empty line...
