### ISSUE TITLE
with lgi how to setup signal callback , like g_signal_connect in c !!

### ISSUE THREAD

**Issue by cppbitman** [pavouk/lgi#119]
like 
         g_signal_connect(dem, "pad-added", G_CALLBACK(demux_pad_added), par);
help!!

**Comment by pavouk** [comment]
Please read the documentation.  Signals are covered even in intro: https://github.com/pavouk/lgi/blob/master/docs/overview.md
This particular case can be written e.g. like this:
```lua
function dem:on_pad_added(...)
    ...
end
```
