### ISSUE TITLE
consider releasing a new git tag

### ISSUE THREAD

**Issue by anthraxx** [pavouk/lgi#127]
Hey,

I would like to ask you if you could consider doing soonish a new git release. Several important bugfixes have been commited since the last release (which is nearly a year ago) that resolve some serious problems f.e. with the awesome WM.
It would be awesome if we could soon see a new release.
cheers

**Comment by psychon** [comment]
Sorry for the spam, but: Which bug fixes are you interested in? I only know about something that breaks the hack I use in awesome (see #125).

**Comment by psychon** [comment]
I think this can be closed.

**Comment by anthraxx** [comment]
0.9.1 has been released with  ba16a14 thx
