### ISSUE TITLE
Menu on StatusIcon it quickly closes

### ISSUE THREAD

**Issue by son-link** [pavouk/lgi#137]
Hi, firt's sorry for my english
I have a problem with submenu on a StatusIcon, this quickly closes when I click on the icon with the right mouse button. What it's the problem?

Menu
```
local menu = Gtk.Menu {visible=true,
	Gtk.ImageMenuItem {
	 	use_stock = true, label = Gtk.STOCK_MEDIA_PLAY,
		on_activate = function()
			play()
		end
	},
  Gtk.ImageMenuItem {
	 	use_stock = true, label = Gtk.STOCK_MEDIA_PREVIOUS,
		on_activate = function()
			prevTrack()
		end
	},
	Gtk.ImageMenuItem {
	 	use_stock = true, label = Gtk.STOCK_MEDIA_NEXT,
		on_activate = function()
			nextTrack()
		end
	},
	Gtk.ImageMenuItem {
	 	use_stock = true, label = Gtk.STOCK_QUIT,
		on_activate = function()
			pipeline.state = 'NULL'
			main_loop:quit()
		end
	}
}
```

The function
```
function statusIcon:on_popup_menu()
	menu:show_all()
	menu:popup(nil, nil, Gtk.status_icon_position_menu, 1, 0)
end
```

**Comment by psychon** [comment]
I cannot help (not much clue about GTK+), but I wonder:

Can you provide a self-contained example? I'd like to have a file that I can just execute and then a status icon appears, I can right-click it and see that the menu immediately closes again (at least I guess that is what should happen).

**Comment by son-link** [comment]
Just i tray your random idea on older release (0.9.0), just like the same program on Python (actually i port a old proyect write on this language) and not work, but now work perflecty :+1: 
Thanks
