### ISSUE TITLE
Error with builder methods.

### ISSUE THREAD

**Issue by v1993** [pavouk/lgi#140]
I'm tried to load my test.ui with builder:

    v@v-mint ~/compile/lgob $ lua -llgi
    Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
    > Gtk = lgi.Gtk
    > builder = Gtk.Builder
    > builder:add_from_file('test.ui')
    /home/v/.luarocks/share/lua/5.2/lgi/override/Gtk.lua:226: bad argument #2 to 'add_from_file' (Gtk.Builder expected, got table)
    stack traceback:
    	[C]: in function 'add_from_file'
    	/home/v/.luarocks/share/lua/5.2/lgi/override/Gtk.lua:226: in function 'add_from_file'
    	stdin:1: in main chunk
    	[C]: in ?
    > =type(builder)
    table
    > =builder
    Gtk.Builder

**Comment by psychon** [comment]
Uhm, you should call `add_from_file` on an instance of the `Gtk.Builder` class. However, you are calling it on the class itself.

Are you perhaps looking for `Gtk.Builder.new_from_file('test.ui')`?
Alternatively:
```lua
local my_builder = Gtk.Builder() -- Note the added () to create an instance of this class
my_builder:add_from_file('test.ui')
```

**Comment by v1993** [comment]
Thank you, you are right!
