### ISSUE TITLE
"Gio asynchronos IO support" does not work for GDBus

### ISSUE THREAD

**Issue by psychon** [pavouk/lgi#142]
I'd expect the following example to work, but it does not. This tries to do async dbus operations with Gio. However, none of the `async_foo`-methods that I'd expect are there.

``` lua
local lgi = require("lgi")
local Gio = lgi.Gio

local bus = Gio.bus_get_sync(Gio.BusType.SYSTEM)

print("Known functions:")
for _, k in ipairs{ "bus_get_sync", "bus_get_async", "bus_get", "bus_get_finish", "async_bus_get" } do
    print(string.format("%15s: %s", k, Gio[k]))
end
print()

print("proxy1", Gio.DBusProxy.new_sync(
    bus,
    Gio.DBusProxyFlags.NONE, nil,
    'org.freedesktop.DBus',
    '/org/freedesktop/DBus',
    'org.freedesktop.DBus',
    nil))

Gio.Async.call(function()
    print(pcall(function()
        print("proxy2", Gio.DBusProxy.async_new(
            bus,
            Gio.DBusProxyFlags.NONE, nil,
            'org.freedesktop.DBus',
            '/org/freedesktop/DBus',
            'org.freedesktop.DBus',
            nil))
    end))
end)()
```

Output:

```
Known functions:
   bus_get_sync: lgi.fun (0x7fda3a500f60): Gio.bus_get_sync
  bus_get_async: nil
        bus_get: lgi.fun (0x7fda3a500fe0): Gio.bus_get
 bus_get_finish: lgi.fun (0x7fda3a5010b0): Gio.bus_get_finish
  async_bus_get: nil

proxy1  lgi.obj 0x564f90cf9d30:Gio.DBusProxy(GDBusProxy)
false   test.lua:22: attempt to call a nil value (field 'async_new')
```

I tried debugging this, but apparently `GObject.Object:_element` from the Gio override (where this auto-async-method-magic seems to be implemented) is never called for GDbus-related values. No idea where to continue debugging.

Edit: After thinking a bit more, I think: This `async_foo` works for methods on objects, but is not yet implemented for static functions. Right?

Edit: And just because I have nowhere else to complain (even though this is the wrong place to complain): GDbus seems to be hard to understand and use when you don't already know it. API docs are nice for providing the details, but I'm missing the part before the details already...

Edit: The following version seems to work, but I consider it ugly. It would be nice if LGI could automatically generate `async_bus_get` etc wrappers.

``` lua
local Gio = require("lgi").Gio

local function skip_first(_, ...)
    return ...
end

Gio.Async.call(function()
    print(pcall(function()
        Gio.bus_get(Gio.BusType.SYSTEM, nil, coroutine.running())
        local bus = Gio.bus_get_finish(skip_first(coroutine.yield()))

        Gio.DBusProxy.new(
            bus,
            Gio.DBusProxyFlags.NONE, nil,
            'org.freedesktop.DBus',
            '/org/freedesktop/DBus',
            'org.freedesktop.DBus',
            nil,
            coroutine.running())
        local a = Gio.DBusProxy.new_finish(skip_first(coroutine.yield()))
        print("proxy:", a)
        return "Done"
    end))
end)()
```

**Comment by pavouk** [comment]
As usual, you nailed it perfectly.  I did not realize when I was implementing this feature that static methods need different codepath, so it is missing.  I'll look at adding it when I'll find some time.

And BTW:
+1 for the rant about GDBus
+1 for the workaround, incl. notice that it is ugly
;-)

**Comment by pavouk** [comment]
I think that this issue is fixed in master.  The test for this uncovered another crash in dbus, but since it looks like unrelated issue, I just commented out offending test and will continue investigating crash later.  Maybe the crash is related to another reported issue regarding connecting dbus signals.

**Comment by psychon** [comment]
Thanks a lot!

For your crash: I cannot reproduce it and I think there might actually be none. The error messages that I saw on Travis points at "`Gio.async_bus_get("SESSION")` failed". So, Lua 5.2 on debian testing seems to be fine.

**Comment by pavouk** [comment]
I can reproduce the crash when connecting to SESSION bus *and* uncommenting proxy creation code in the test. It probably cannot be reproduced on travis since travis environment seems to choke at attempt to create any 'SESSION' bus.

From the backtrace of the crash it really looks like some issue deep inside gdbus when connecting signals (I think, I didn't have time to investigate this yet,  the 'simple' issue of making async_ stuff work for static and global functions took me almost whole weekend.  The _element/_access/category/component.mt machinery is really an unholy mess which would deserve to be completely removed and replaced with something genially simple and fast... alas, I don't know that 'something' yet... ).

**Comment by psychon** [comment]
Heh. Whoops.
I can reproduce the bug like this:
```diff
diff --git a/tests/gio.lua b/tests/gio.lua
index 8c6635d..200e3ef 100644
--- a/tests/gio.lua
+++ b/tests/gio.lua
@@ -64,13 +64,13 @@ function gio.async_access()
    check(res ~= nil)
 
    local b = Gio.Async.call(function()
-                              return Gio.async_bus_get('SYSTEM')
+                              return Gio.async_bus_get('SESSION')
    end)()
    check(Gio.DBusConnection:is_type_of(b))
 
    -- Disable randomly crashing test until issue with random dbus
    -- crashes is resolved.
-   if false then
+   if true or false then
    local proxy = Gio.Async.call(function(bus)
                                   return Gio.DBusProxy.async_new(
                                      bus, 'NONE', nil,
```
and I can fix it with this patch:
```diff
diff --git a/tests/dbus.lua b/tests/dbus.lua
index 7cfae57..f9487e6 100644
--- a/tests/dbus.lua
+++ b/tests/dbus.lua
@@ -124,6 +124,7 @@ function dbus.info_xml()
 end
 
 function dbus.proxy_get_interface_info()
+       if true then return end
    local Gio = lgi.Gio
 
    -- This test does not actually test much, it only checks for a double-free due
```
However, I didn't find any "good" fix for this. Perhaps the `TestDBus`-stuff should be moved into a higher level (`tests/tests.lua`) and only be done once?

**Comment by pavouk** [comment]
I have spent some time and I agree that it is some fishy thing with Gio.TestDBus.  I can get crash with this code:

```lua
local test_dbus = Gio.TestDBus.new('NONE')
test_dbus:up()
local bus = Gio.bus_get_sync('SESSION')
test_dbus:down()

local test_dbus = Gio.TestDBus.new('NONE')
test_dbus:up()
local bus = Gio.bus_get_sync('SESSION')
test_dbus:down()
```

but I'm not sure why, this looks like correct usage to me.  Maybe TestDBus does not like having non-destroyed bus instance when calling down?  I'll continue investigating that later...

**Comment by psychon** [comment]
Fun fact 1: Your code does not crash here (but starts crashing if I add a call to `bus:flush()` (because I really meant `bus:flush_sync()`, but not this async operation keeps the bus alive)).
Fun fact 2: The crash is because the `GDBusConnection`'s `worker` member is a NULL pointer, i.e. things are using an instance of `GDBusConnection` that was already disposed (yup, I looked at the source code in glib). So, whatever `test_dbus:down()` is trying to do to ensure that the session bus instance of `GDBusConnection` is gone, it does not work.
