### ISSUE TITLE
Callback lifetime issue with g_dbus_connection_signal_subscribe

### ISSUE THREAD

**Issue by psychon** [pavouk/lgi#143]
The following code tries to listen to all DBus signals and prints them.

The code (likely) crashes as soon as the second signal comes in. I didn't do any debugging, but I guess that lgi expects the callback to only be called once (and that some annotations are wrong and so the GDestroyNotify argument isn't recognized):

``` lua
local lgi = require("lgi")
local GLib = lgi.GLib
local Gio = lgi.Gio

local function skip_first(_, ...)
    return ...
end

local function main()
    Gio.bus_get(Gio.BusType.SESSION, nil, coroutine.running())
    local bus = Gio.bus_get_finish(skip_first(coroutine.yield()))

    bus:signal_subscribe(nil, nil, nil, nil, nil, Gio.DBusSignalFlags.NONE, function(...)
        print("Got signal", ...)
    end)
    coroutine.yield() -- Just keep us alive forever
end

local function error_handler(err)
    print(debug.traceback(tostring(err), 2))
end

local success, msg = Gio.Async.call(xpcall)(main, error_handler)
if not success then
    print(msg)
end
```

Feel free to ignore this report since apparently GDBus isn't easily usable and even less so via lgi. I guess I'll never have good lua-dbus-bindings. :-(

**Comment by TingPing** [comment]
> Feel free to ignore this report since apparently GDBus isn't easily usable and even less so via lgi.

It isn't *that* bad even if a bit ugly. I thought about making some more lua-like wrappers but I probably am not the best to do it.

Few scripts I have using it:
- https://github.com/TingPing/plugins/blob/master/HexChat/nowplaying.lua
- https://github.com/TingPing/plugins/blob/master/HexChat/screensaver.lua

**Comment by psychon** [comment]
@TingPing Yeah, well, I was hoping for some usable high-level bindings, but those apparently all require the use of generated C code.
For improving the code a bit: Do you know about lgi's [`Gio.Async`](https://github.com/pavouk/lgi/blob/master/docs/gio.md)? That's really a neat idea that makes asynchronous code a lot more readable, I think.

How well does your screensaver.lua work?
It should be affected by exactly the crash bug that I am reporting here. Since it works for you, apparently it is (at least) sometimes safe? I was testing this on an up-to-date Debian testing system with either Lua5.1 or Lua5.2 (I don't remember). [Apparently](https://packages.debian.org/sid/libglib2.0-0) this means glib 2.49.7-1.
Right now I'm on an up-to-date Fedora 23 with Lua 5.3.3 and the above program immediately crashed when I ran `notify-send foo` in another terminal. The file `Gio-2.0.typelib` is owned by package gobject-introspection-1.48.0-1.fc24.x86_64 (Debian seems to have version 1.49.1-2 of this).

**Comment by psychon** [comment]
This issue seems to be more complicated than I initially thought. The following program crashes (for me) if you set `crash=true`, but works fine with `crash=false`. Apparently the status (dead / yielded) of a coroutine that is never explicitly mentioned makes quite a difference here. (Thanks to @TingPing for making me find this!)
```lua
local lgi = require("lgi")
local Gio = lgi.Gio

local crash = true

local function main()
    local bus = Gio.bus_get_sync(Gio.BusType.SESSION)

    bus:signal_subscribe(nil, nil, nil, nil, nil, Gio.DBusSignalFlags.NONE, function(...)
        print("Got signal", ...)
    end)
    if crash then
        coroutine.yield()
    end
end

coroutine.resume(coroutine.create(main))
lgi.GLib.MainLoop.new():run()
```
The only two calls to `lua_status()` in lgi is in `lgi/callable.c`, function `closure_callback` (that sounds quite related!). According to `valgrind`, in the crash-case `lua_status(NULL)` is called. This sounds the `lua_tothread()` call [here](https://github.com/pavouk/lgi/blob/70b85a6755eba1a63fd217755109f781e3570f58/lgi/callable.c#L1110) returns `NULL`. I'll verify this theory and leave an edit here, but I don't think I have enough clue to fix this (no idea how this is supposed to work).

**Comment by TingPing** [comment]
> For improving the code a bit: Do you know about lgi's Gio.Async? 

I tried it briefly and it seemed to block the UI so I never looked into that, perhaps I did something wrong.

> How well does your screensaver.lua work?

I have experienced crashes subscribing to signals but that exact script works fine. I can try to repro it again and try out your patch.

**Comment by psychon** [comment]
@TingPing "Blocking the UI" sounds like Gio.Async.start vs Gio.Async.call (one of them is "blocking asynchronous", the other one isn't). However, with this you'd then definitely run into the crashes that I am seeing.
Thanks for the offer, but no, I don't think there is much point in trying out my patch. I'll just let this wait for @pavouk's wisdom.

**Comment by psychon** [comment]
This is likely the same issue as #155 (the code around there looked familiar to me and now I remember why: because I already stared it when working on this bug). The patch from #155 also fixes this issue. I'll try to turn it into a pull request later.
