### ISSUE TITLE
GObject-Object.lua:100: bad argument #8 to 'object_new'

### ISSUE THREAD

**Issue by folknor** [pavouk/lgi#167]
Hi,
So I was having this issue:
```
lua5.2: .../.luarocks/share/lua/5.2/lgi/override/GObject-Object.lua:100: bad argument #8 to 'object_new' (string expected, got userdata)
stack traceback:
	[C]: in function 'object_new'
	.../.luarocks/share/lua/5.2/lgi/override/GObject-Object.lua:100: in function '_construct'
	.../.luarocks/share/lua/5.2/lgi/override/GObject-Object.lua:216: in function <.../.luarocks/share/lua/5.2/lgi/override/GObject-Object.lua:215>
	(...tail calls...)
	test.lua:8: in main chunk
	[C]: in ?

```

And was trying to figure it out when I decided to go through the bug reports here on github, and this latest issue provides a good test case:
https://github.com/pavouk/lgi/issues/166

Copy+paste that code into test.lua, run it, and get the result above.
```
$ apt-cache show luarocks | grep Version
Version: 2.4.2+dfsg-1
$ apt-cache show gobject-introspection | grep Version
Version: 1.53.2-4
$ apt-cache show libglib2.0-0 | grep Version
Version: 2.53.4-3
```

**Comment by psychon** [comment]
I seem to be missing the point. If you are saying that you run into #166, why are you opening a new issue for it?

**Comment by vhaarr** [comment]
Ah, yes, I should probably have been more clear.
This is not the same issue, but #166 has a tiny testcase that works for this as well.

Here is a even smaller test case, based on the one from #166.

```lua
#! /usr/bin/env lua
local lgi = require 'lgi'
local Gtk = lgi.Gtk
local w = Gtk.Window {}
Gtk.main()
```

**Comment by psychon** [comment]
Okay, what error message do you get when running that example? (I'm curious about the line numbers in the stack trace)
Also, could you try running with gobject-introspection from testing? Your version seems to be the one from Debian unstable and this seems like a likely culpit for the breakage.

**Comment by vhaarr** [comment]
Certainly, the error is obviously the same as in comment 1, but the line numbers in this stack are from the 5-line example given in comment 3.

Also it now says that the error is "bad argument #4" instead of #8, probably because the offending line changed from `Gtk.Button { label = "click me!", id = "btn" }` to `local w = Gtk.Window {}`

```
$ lua test.lua 
lua: .../.luarocks/share/lua/5.2/lgi/override/GObject-Object.lua:100: bad argument #4 to 'object_new' (table expected, got nil)
stack traceback:
	[C]: in function 'object_new'
	.../.luarocks/share/lua/5.2/lgi/override/GObject-Object.lua:100: in function '_construct'
	.../.luarocks/share/lua/5.2/lgi/override/GObject-Object.lua:216: in function <.../.luarocks/share/lua/5.2/lgi/override/GObject-Object.lua:215>
	(...tail calls...)
	test.lua:4: in main chunk
	[C]: in ?
```

So I downgraded gobject-introspection and libgirepository-1.0-1 to 1.50.0-2 from https://packages.debian.org/source/buster/gobject-introspection and the results seem to be the same. I did not downgrade any other packages from that source (for example libgirepository1.0-dev), and the only thing I did after dpkg -i completed was opening a new tty to get a somewhat fresh environment, then I ran it again:
```
$ lua test.lua 
lua: .../.luarocks/share/lua/5.2/lgi/override/GObject-Object.lua:100: bad argument #4 to 'object_new' (table expected, got nil)
stack traceback:
	[C]: in function 'object_new'
	.../.luarocks/share/lua/5.2/lgi/override/GObject-Object.lua:100: in function '_construct'
	.../.luarocks/share/lua/5.2/lgi/override/GObject-Object.lua:216: in function <.../.luarocks/share/lua/5.2/lgi/override/GObject-Object.lua:215>
	(...tail calls...)
	test.lua:4: in main chunk
	[C]: in ?
```

**Comment by vhaarr** [comment]
Right, so I thought about it a second time, and then I downgraded https://packages.debian.org/buster/gir1.2-glib-2.0 from 1.53.2-4 to 1.50.0-2, and now there is no error.

**Comment by vhaarr** [comment]
https://developer.gnome.org/gobject/2.53/gobject-The-Base-Object-Type.html#g-object-newv

**Comment by psychon** [comment]
Ah, they changed the API. Great.
Possible patch (completely untested):
```diff
diff --git a/lgi/override/GObject-Object.lua b/lgi/override/GObject-Object.lua
index bb59883..83370fa 100644
--- a/lgi/override/GObject-Object.lua
+++ b/lgi/override/GObject-Object.lua
@@ -67,7 +67,7 @@ function Object:_construct(gtype, param, owns)
    if object then return object end
 
    -- Process 'args' table, separate properties from other fields.
-   local parameters, others, safe = {}, {}, {}
+   local names, values, parameters, others, safe = {}, {}, {}
    for name, arg in pairs(param or {}) do
       if type(name) == 'string' then
         local argtype = self[name]
@@ -90,6 +90,9 @@ function Object:_construct(gtype, param, owns)
            local marshaller = Value.find_marshaller(gtype, argtype.typeinfo)
            marshaller(value, nil, arg)
            parameters[#parameters + 1] = parameter
+
+           names[#names + 1] = name
+           values[#values] = parameter
         else
            others[name] = arg
         end
@@ -97,7 +100,7 @@ function Object:_construct(gtype, param, owns)
    end
 
    -- Create the object.
-   object = object_new(gtype, parameters)
+   object = object_new(gtype, names, values)
 
    -- Perform initialization on interfaces.
    if next(self._implements) then
```
Instead of `object = object_new(gtype, names, values)` possible it needs to be `object = object_new(gtype, #names, names, values)`. I'm not sure about the magic that adds array lengths here.

Alternatively, the following might also work:
```diff
diff --git a/lgi/override/GObject-Object.lua b/lgi/override/GObject-Object.lua
index bb59883..4a8db39 100644
--- a/lgi/override/GObject-Object.lua
+++ b/lgi/override/GObject-Object.lua
@@ -39,7 +39,7 @@ end
 -- to initialize.
 local parameter_repo = repo.GObject.Parameter
 local object_new = gi.GObject.Object.methods.new
-if object_new then
+if false and object_new then
    object_new = core.callable.new(object_new)
 else
    -- Unfortunately, older GI (<1.30) does not export g_object_newv()
```
Since I do not have much clue about GI, I'll leave this to @pavouk.

**Comment by psychon** [comment]
And one last possible patch (I see that the rename of `newv` to `new` is gone, so it might be okay to just continue using `newv` for the time being):
```diff
diff --git a/lgi/override/GObject-Object.lua b/lgi/override/GObject-Object.lua
index bb59883..9227ef7 100644
--- a/lgi/override/GObject-Object.lua
+++ b/lgi/override/GObject-Object.lua
@@ -38,7 +38,7 @@ end
 -- Object constructor, 'param' contains table _with properties/signals
 -- to initialize.
 local parameter_repo = repo.GObject.Parameter
-local object_new = gi.GObject.Object.methods.new
+local object_new = gi.GObject.Object.methods.newv or gi.GObject.Object.methods.new
 if object_new then
    object_new = core.callable.new(object_new)
 else
```

**Comment by folknor** [comment]
> And one last possible patch

This last patch seems to get things working again, by itself.
Thank you!

**Comment by TingPing** [comment]
Just bumping that last patch, would be nice to get it in a realize before GLib 2.54 is out.

**Comment by ildar** [comment]
hi!
with 0.9.2 + Glib2 2.64.5 I get:
> Gio.DBusObjectManagerClient.new_sync(
Gio.bus_get_sync(Gio.BusType.SYSTEM), "org.bluez", "/")

stdin:1: bad argument #-1 to 'new_sync' (number expected, got nil)
stack traceback:
[C]: in field 'new_sync'
stdin:1: in main chunk
[C]: in ?

Is this again the API breakage or something?

**Comment by psychon** [comment]
Why do you think so? Did that ever work? According to [the API docs](https://developer.gnome.org/gio/stable/GDBusObjectManagerClient.html#g-dbus-object-manager-client-new-sync), the second argument should be some flags. Adding a `0` argument here works (thanks to all those nullable arguments...):
```
lua -e 'lgi = require("lgi"); gio = lgi.Gio; gio.DBusObjectManagerClient.new_sync(gio.bus_get_sync(gio.BusType.SYSTEM), 0, "org.bluez", "/")'
```

**Comment by ildar** [comment]
my fault. "Deep night effect". Thanks for your help!
