### ISSUE TITLE
New release wanted

### ISSUE THREAD

**Issue by ntd** [pavouk/lgi#175]
Just to highlight the fact that #167 brake ~~everything~~ my application on archlinux (that now ships glib-2.54.0).

**Comment by rokf** [comment]
Same for Alpine Linux (edge).

**Comment by pavouk** [comment]
Released. I really apologize for not getting to do it sooner.

**Comment by psychon** [comment]
Thanks a lot! I hope you are well and there were no "good reasons" why it took so long. ;-)
