### ISSUE TITLE
error in install

### ISSUE THREAD

**Issue by sbh96** [pavouk/lgi#176]
hi, i have problem in install ubuntu 16 .
when i use this command 
`luarocks install lgi`
return me this erorr

`Installing https://luarocks.org/lgi-0.9.2-1.src.rock
make -C lgi
make[1]: Entering directory '/tmp/luarocks_lgi-0.9.2-1-FzYS4O/lgi/lgi'
pkg-config --exists 'gobject-introspection-1.0 >= 0.10.8' --print-errors
Package gobject-introspection-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-introspection-1.0' found
Makefile:53: recipe for target '.depcheck' failed
make[1]: *** [.depcheck] Error 1
make[1]: Leaving directory '/tmp/luarocks_lgi-0.9.2-1-FzYS4O/lgi/lgi'
Makefile:16: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.`

where is problem?

**Comment by TingPing** [comment]
Install the dev package for gobject-introspection.

**Comment by psychon** [comment]
...which is `libgirepository1.0-dev` in Debian and thus likely also in Ubuntu.
