### ISSUE TITLE
Error installing lgi via luarocks

### ISSUE THREAD

**Issue by HellScre4m** [pavouk/lgi#179]
Hi I get this while trying to install:
```
luarocks install lgi
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/lgi-0.9.2-1.src.rock...
Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/lgi-0.9.2-1.src.rock... switching to 'build' mode
make -C lgi
make[1]: Entering directory '/tmp/luarocks_lgi-0.9.2-1-9083/lgi/lgi'
pkg-config --exists 'gobject-introspection-1.0 >= 0.10.8' --print-errors
Package gobject-introspection-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-introspection-1.0' found
Makefile:53: recipe for target '.depcheck' failed
make[1]: *** [.depcheck] Error 1
make[1]: Leaving directory '/tmp/luarocks_lgi-0.9.2-1-9083/lgi/lgi'
Makefile:16: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by psychon** [comment]
> Package gobject-introspection-1.0 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'gobject-introspection-1.0' found

So, what do you now expect from me that this error message does not already tell you? You do not have the development files for gobject-introspection installed. When `pkg-config --modversion gobject-introspection-1.0` starts to work, compiling lgi will also start to work.

**Comment by artur233945** [comment]
The required package is `libgirepository1.0-dev`, if you're debian-based.
Funny when answer is shorter than the rant :)
```
sudo apt-get install libgirepository1.0-dev
```
