### ISSUE TITLE
Strange GLib.Variant

### ISSUE THREAD

**Issue by v1993** [pavouk/lgi#180]
After some work with DBus I found very strange `GLib.Variant` as answer to property request via `org.freedesktop.DBus.Properties`. My variable is `metadata`:

    metadata = props:Get("org.mpris.MediaPlayer2.Player", "Metadata") -- wrapper around DBusProxy
    for k,v in metadata:pairs() do print(k,v.value) end -- Everything works fine
    print('FAIL HERE')
    for k,v in metadata:pairs() do print(k,metadata[k].value) end -- GLib.Variant: no `some field'

Example:

    bitrate	128	
    mpris:artUrl	file:///tmp/clementine-art-UX1706.jpg	
    mpris:trackid	/org/mpris/MediaPlayer2/Track/43	
    xesam:artist	lgi.rec 0x7f885c005e90:GLib.Variant
    xesam:genre	lgi.rec 0x2882b80:GLib.Variant
    xesam:title	The Untouchables - Level 2	
    xesam:url	http://streaming.rolandradio.net:80/rolandradio	
    FAIL HERE	
    /usr/bin/lua: current_mus.lua:33: GLib.Variant: no `bitrate'
    stack traceback:
    	[C]: in function 'error'
    	/home/v/.luarocks/share/lua/5.2/lgi/component.lua:160: in function </home/v/.luarocks/share/lua/5.2/lgi/component.lua:156>
    	[C]: in function '__index'
    	current_mus.lua:33: in main chunk
    	[C]: in function 'dofile'
    	/home/v/.luarocks/lib/luarocks/rocks/trepl/scm-1/bin/th:143: in main chunk
    	[C]: in ?

**Comment by v1993** [comment]
Here's `prop:Get` function:

	return self._proxy:call_sync(
		'Get',
		GLib.Variant.new_tuple(
		{
				GLib.Variant("s",interface);
				GLib.Variant("s",property);
		}, 2),
		Gio.DBusConnectionFlags.NONE,
		-1, -- Timeout
		nil -- Cancellable
	)

**Comment by psychon** [comment]
> for k,v in metadata:pairs() do print(k,metadata[k].value) end

Correct me if I am wrong, but the docs do not say that the above should work, do they?
https://github.com/pavouk/lgi/blob/master/docs/variant.md#data-access

**Comment by v1993** [comment]
`metadata[k] == v`, right?

**Comment by psychon** [comment]
Your bug report says that this is not the case, so no.
Also, I am pointing at the docs and basically say "I am not sure, but the docs only say something about integer indices". So this is another "no".

Are you perhaps looking for `metadata.value[k]` (but this only works with string keys, not with integer keys, I think...)?

**Comment by v1993** [comment]
Yes, it really works using `metadata.value[k]`.  Now ther's another strange moment:

    org.freedesktop.DBus.Properties.Get (in STRING interface_name,
                                         in STRING property_name,
                                         out VARIANT value);
    org.freedesktop.DBus.Properties.Set (in STRING interface_name,
                                         in STRING property_name,
                                         in VARIANT value);
    org.freedesktop.DBus.Properties.GetAll (in STRING interface_name,
                                            out DICT<STRING,VARIANT> props);
Type of `Metadata` property is also `DICT<STRING,VARIANT>`. But result of `GetAll(...)[1]` is table, and result of `Get(...)[1]` is Variant. Why?

**Comment by psychon** [comment]
> But result of GetAll(...)[1] is table,

It is a table with string keys and Variant values, right? So it is `DICT<STRING,VARIANT>`.

> and result of Get(...)[1] is Variant. Why?

Sorry, what is the question exactly? You quote the documentation that says that `Get` returns a variant and `GetAll` returns a mapping from strings to variants and then you ask just why you get these result??

Closing under the assumption that there is no bug here to fix.

**Comment by v1993** [comment]
I think, I understood... a bit strange for me, but OK.
