### ISSUE TITLE
How can I use lgi with any GObject library?

### ISSUE THREAD

**Issue by rucuriousyet** [pavouk/lgi#187]
Im looking to use librsvg to load svg files into Cairo for editing using this library. How can I create the required wrapping etc for librsvg (which has a GObject api)? I took a look at the docs and didn't find anything useful for this.

**Comment by TingPing** [comment]
```lua
local lgi = require('lgi')
local Rsvg = lgi.require('Rsvg', '2.0')
```

**Comment by psychon** [comment]
Google gave me https://www.cairographics.org/cookbook/librsvgpython/ as an example for RSvg and with that I came up with the following code:
```lua
lgi = require("lgi")
rsvg = lgi.Rsvg
handle = rsvg.Handle.new_from_file("/usr/lib/libreoffice/share/gallery/symbols/Shield01.svg")
dim = handle:get_dimensions()
print(dim.width, dim.height)
-- Just to check if handle:render_cairo() exists, as I would expect from the link above.
print(handle.render_cairo)
```
I'm not quite sure what you mean with "the required wrapping etc for librsvg". If you mean stuff like what we have in `lgi/override/`: That's only needed to work around problems in the wrapping, make stuff easier to use, and provide a more "lua-like" API.
