### ISSUE TITLE
g_variant_iter_*?

### ISSUE THREAD

**Issue by kalkbrenner** [pavouk/lgi#201]
Hi,

I tried to access a GVariant dictionary (which is returned as table proxy) and iterate via pairs() which of course failed (as the documentation mentions).

https://github.com/pavouk/lgi/blob/master/docs/variant.md:
> Dictionaries return proxy table which can be indexed by dictionary keys to retrieve dictionary values. Generic arrays are not automatically expanded, the source variants are returned are returned instead.

I wanted to extend https://github.com/pavouk/lgi/blob/8535e8012c70b230d30ebb5fc4326f9b9a65451d/lgi/override/GLib-Variant.lua#L221 and implement a __pairs metamethod with g_variant_iter_* functions which (I thought) should be available via something like Glib.VariantIter - but that doesn't exist.

How can I access the functions like
- https://developer.gnome.org/glib/stable/glib-GVariant.html#g-variant-iter-init
- https://developer.gnome.org/glib/stable/glib-GVariant.html#g-variant-iter-next

Bye
Björn

**Comment by psychon** [comment]
> How can I access the functions like

You cannot. They are marked as `[skip]` which means that language bindings should ignore these functions.
Sorry, but this is not LGI's fault 

Why do you want `g_variant_iter_init` instead of `g_variant_iter_new`? The later seems to be the way to go and they do practically the same thing (for Lua; since you cannot allocate anything "on the stack").
The alternative to `g_variant_iter_next` seems to be `g_variant_iter_next_value`, but I am not quite sure. `GVariant` is always a mystery to me.

**Comment by kalkbrenner** [comment]
:pairs() is not working on "a{sv}" (dictionary), i tried that before. It is working on a returned "standard" Variant, but not on that specific type which is converted by lgi. I looked at the source Lines mentioned, that is really only returning a proxy metatable.
*_value also needs a GVariantIter to store the iteration state (i think).
https://developer.gnome.org/glib/stable/glib-GVariant.html#g-variant-iter-next-value

Even if i can use g_variant_iter_new(), how can i call it from Lua? Is it mapped to GVariant? 
Iter = GVariant:iter_new()?

What am trying is to get the list of keys returned in the dict ("a{sv}").
The complete signature of my message is more complex, "ua{sv}as" i think, it's returned from systemd via DBus when a unit had changed it's state, throwing the PropertiesChanged" signal.
The proxy table is returned as e.g. var.value[2] which is also correct - but i can't iterate the keys, just access them directly (which calls _lookup_value(...) on the Variant dict via metatable.

**Comment by kalkbrenner** [comment]
You mentioned skip. Due to the fact that i am completely new to lgi and the introspection and auto generation, my questions seem to be a bit stupid ;)

Where can i see which functions are mapped? I also tried to understand the Lua C code but failed this time...

**Comment by psychon** [comment]
> Where can i see which functions are mapped?

It's in the API docs. In the line before "Parameters" in https://developer.gnome.org/glib/stable/glib-GVariant.html#g-variant-iter-init it says `[skip]`. If you mouse-over, it shows that this means that this function is "not necessarily available in other languages [other than C]". Basically, with such an annotation, lgi does not get any information about the function from GObject-Introspection and thus cannot make it available.

**Comment by psychon** [comment]
> The complete signature of my message is more complex, "ua{sv}as" 

Well... GLib says `Variant.new('ua{sv}as') - invalid type`, so that cannot be it.

> What am trying is to get the list of keys returned in the dict ("a{sv}").

For this, `:pairs()` works for me:
```lua
GLib = require("lgi").GLib
something = GLib.Variant("s", "Hello")
v = GLib.Variant("a{sv}", { first = something, second = something})

for k, v in v:pairs() do
	print(k, v:print())
end
```
Output is
```
first	'Hello'
second	'Hello'
```
So, if you really just want the list of all keys:
```lua
local keys = { }
for k in v:pairs() do
	table.insert(keys, k)
end
-- keys is now the list of all keys
```

**Comment by kalkbrenner** [comment]
My fault, not ua{sv}as but sa{sv}as but, to be exact, here is the message I am talking about, output with :print():
```
msg	Type:    signal
Flags:   no-reply-expected
Version: 0
Serial:  543
Headers:
  path -> objectpath '/org/freedesktop/systemd1/unit/someservice_2eservice'
  interface -> 'org.freedesktop.DBus.Properties'
  member -> 'PropertiesChanged'
  sender -> ':1.1'
  signature -> signature 'sa{sv}as'
Body: ('org.freedesktop.systemd1.Unit', {'ActiveState': <'active'>, 'SubState': <'running'>, 'StateChangeTimestamp': <uint64 1535655871317776>, 'StateChangeTimestampMonotonic': <uint64 41543070167>, 'InactiveExitTimestamp': <uint64 1535655871317776>, 'InactiveExitTimestampMonotonic': <uint64 41543070167>, 'ActiveEnterTimestamp': <uint64 1535655871317776>, 'ActiveEnterTimestampMonotonic': <uint64 41543070167>, 'ActiveExitTimestamp': <uint64 1535655835404998>, 'ActiveExitTimestampMonotonic': <uint64 41507157395>, 'InactiveEnterTimestamp': <uint64 1535655835595100>, 'InactiveEnterTimestampMonotonic': <uint64 41507347496>, 'Job': <(uint32 0, objectpath '/')>, 'ConditionResult': <true>, 'AssertResult': <true>, 'ConditionTimestamp': <uint64 1535655871156086>, 'ConditionTimestampMonotonic': <uint64 41542908479>, 'AssertTimestamp': <uint64 1535655871156094>, 'AssertTimestampMonotonic': <uint64 41542908485>}, @as [])
UNIX File Descriptors:
  (none)
```

And the error-message:
```
(process:1401): Lgi-WARNING **: Error raised while calling 'lgi.cbk (function: 0x656fe0): Gio': ./signal_subscribe.lua:126: attempt to call a nil value (method 'pairs')
```

and the part of the code:
```
   bus:add_filter(function(a, msg, ...)
    local path = msg:get_path()
    local member = msg:get_member()
    local interface = msg:get_interface()

    if msg:get_message_type() == "SIGNAL" and
        member == "PropertiesChanged" and
        interface == "org.freedesktop.DBus.Properties"
    then
      local body = msg:get_body()
      print("interface",body.value[1])
      for k,v in body.value[2]:pairs() do
         print("data:",k,v)
      end 
    end
```
where the "for k,v in body.value[2]:pairs() line is :126 from the error message.

This matches perfect with the code in https://github.com/pavouk/lgi/blob/8535e8012c70b230d30ebb5fc4326f9b9a65451d/lgi/override/GLib-Variant.lua#L212.

In https://github.com/pavouk/lgi/blob/8535e8012c70b230d30ebb5fc4326f9b9a65451d/lgi/override/GLib-Variant.lua#L216 the type 'a{s*}' is matched, a new metatable is created with only __index defined and this metatable is attached to a complete, empty Lua table in https://github.com/pavouk/lgi/blob/8535e8012c70b230d30ebb5fc4326f9b9a65451d/lgi/override/GLib-Variant.lua#L236 which is then returned. 
I have also done some print() lines to be really sure that this code is triggered - it is, exactly at this position and there is no pairs() function defined as table member, it is just that proxy table.
If I access that table with the correct key index, the lookup in line 219 is done and the value is returned - but, as mentioned, I can't get the keys of the table, they simply don't exist.

Yes, I just want to use pairs() just like in your last code example but no, it is not working :)

**Comment by terminar** [comment]
(sorry, switched GitHub account)

@psychon I tried your example, it worked also on my side. 

I dived a little bit deeper into the Glib-Variant.lua and realised that the a{sv} can also be accessed just like arrays, even if they are dictionaries. I have added a merge request as possible solution. It's working here with my code, maybe this is also interesting for lgi in general.

I think currently it is a bit irritating to have :pairs() as a method, but regarding compatibility with Lua 5.1 (and array data types) it seems to be reasonable. 

Having __pairs for a dictionary like the code in the merge request will be a nice addon. There shouldn't be a pairs method returned from the dict table, the metatable seems to be the only correct implementation for me.

**Comment by psychon** [comment]
> @psychon I tried your example, it worked also on my side.

I'll interpret this as "this issue can be closed". Glad that it works. :-)
(And yes, this stuff is not easy for me as well and I always have to fight to get the data out of DBus messages)
