### ISSUE TITLE
What is GLib.timeout_add_seconds first argument?

### ISSUE THREAD

**Issue by v1993** [pavouk/lgi#204]
I have to call `GLib.timeout_add_seconds` like

    lgi.GLib.timeout_add_seconds(
        10, -- What is it?
        1, -- Time
        function() print(42) return true end -- Callback
    )
What first argument does?

**Comment by TingPing** [comment]
Probably the priority: https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-timeout-add-seconds-full

So you want `GLib.PRIORITY_DEFAULT`

**Comment by TingPing** [comment]
It was just a guess, but yes that would be confusing. The `_full()` variant doesn't actually make sense in bindings though since the userdata argument isn't needed. So maybe it was just decided to only have one with the priority.

**Comment by psychon** [comment]
> Probably the priority: https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-timeout-add-seconds-full

Note that the docs for this functions contain:

> [rename-to g_timeout_add_seconds]

So yes, `timeout_add_seconds` is indeed `timeout_add_seconds_full`. Also, I vaguely remember some lifetime-magic that makes GObject-Introspection users auto-magically able to use `GDestroyNotify` arguments to get the lifetime of things like `GSourceFunc` and `gpointer data` right. So, it might be that this magic consumes the `GDestroyNotify` argument internally.
If this answer is not satisfactory to you, I can try finding a pointer to that magic.

Is this answer satisfactory? Can this be closed?

**Comment by v1993** [comment]
Yeah, now I got everything what I need.
