### ISSUE TITLE
GTK and glade does not run together (signal SIGSEGV problem)

### ISSUE THREAD

**Issue by Farukklav** [pavouk/lgi#217]
Hello. I work for on GUI app on my olimex development kit with codeblocks. I created interface on glade and I tried run glade with gtk-3.0 on codeblocks but I took `program recived signal SIGSEGV, segmentation fault` error every time.  I did debug and error return on `gtk_widget_show(window)` line. I took same error other my code experiments. I struggle with this error since 3 days. My code this: 

    #include <stdlib.h>
    #include <gtk/gtk.h>

    int main(int argc, char *argv[])
    {
    GtkBuilder *builder;
    GtkWidget *window;
    GError *err = NULL;

    gtk_init(&argc, &argv);

    builder=gtk_builder_new();
    gtk_builder_add_from_file(builder, "/home/olimex/Desktop/New1/box_test/GUI.glade", NULL);

    //window=GTK_WIDGET(gtk_builder_get_object(builder,"GUI"));
    if (NULL==window)
    {
        fprintf(stderr, "Unable to file object with id \"GUI\" \n");
    }
    gtk_builder_connect_signals(builder, NULL);

    g_object_unref(builder);

    gtk_widget_show(window);
    gtk_main();

    }

     void on_window_main_destroy()
    {
     gtk_main_quit();
     }

How can I fix this error? Thanks.

**Comment by psychon** [comment]
Uhm... sorry, but where does LGI / Lua come into play here? You do not seem to be using LGI.

**Comment by Farukklav** [comment]
I thought we could open a general topic. Sorry.

**Comment by Farukklav** [comment]
Thanks for your reply. I exceed segmentation error bu now I take `Gtk-CRITICAL**: gtk_widget_show: assertion_failure 'GTK_IS_WIDGET(widget error)' failed` now. These problems really make you tired. I will go on research thanks.

**Comment by psychon** [comment]
What's the content of `/home/olimex/Desktop/New1/box_test/GUI.glade`?

**Comment by Farukklav** [comment]
This is glade file for create GUI.
