### ISSUE TITLE
lua.h: No such file or directory - compiling error

### ISSUE THREAD

**Issue by frstrich** [pavouk/lgi#219]
I tried the installation via the installation instructions in the readme. Im using a Lubuntu 18.10. After cloning the git-repo and installing the libgirepo(...)  i tried executing `make` in the lgi folder and got the following error message: 

```
username@lubuntu:/tmp$ sudo make -C lgi
make: Entering directory '/tmp/lgi'
make -C lgi
make[1]: Entering directory '/tmp/lgi/lgi'
pkg-config --exists 'gobject-introspection-1.0 >= 0.10.8' --print-errors
touch .depcheck
cc -fPIC   -pthread -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wall -Wextra -O2 -g -c -o buffer.o buffer.c
In file included from buffer.c:12:
lgi.h:11:10: fatal error: lua.h: No such file or directory
 #include <lua.h>
          ^~~~~~~
compilation terminated.
make[1]: *** [Makefile:65: buffer.o] Error 1
make[1]: Leaving directory '/tmp/lgi/lgi'
make: *** [Makefile:16: all] Error 2
make: Leaving directory '/tmp/lgi'
```

The confusing part is, that i have lua5.1 and lua5.1-dev installed (i also tried 5.3 - didnt work). I searched my harddrive for any lua.h and found it in `/usr/include`. Since i had no idea what I was doing, i tried inserting that path into the `/lgi/lgi/Makefile` (by deleting the path in the line "LUA_LIBDIR = " and replacing it with `/usr/include/lua5.1`) but without any success - the error stayed the same. I have  never worked with compiling sourcecode before so i have no clue what to do now (tbh also never had a clue beforehand). Greatfull for any suggestions.

**Comment by psychon** [comment]
Try `make LUA_CFLAGS=-I/usr/include/lua5.1`.

**Comment by frstrich** [comment]
That seems to be the solution. It does output a warning
 ```
object.c: In function ‘object_new’:
object.c:576:7: warning: ‘g_object_newv’ is deprecated: Use 'g_object_new_with_properties' instead [-Wdeprecated-declarations]
```
but i think that can be ignored (?). It does not exit early and `checkinstall` had no problems so it seems to be working as intended. Thank you very much!

**Comment by psychon** [comment]
Yup, that warning can be ignored. I'm closing this, but feel free to keep asking questions.

**Comment by areeseofcake** [comment]
I have this same issue, only I am trying to use luarocks.
`
sudo luarocks install lgi`

```
Installing https://luarocks.org/lgi-0.9.2-1.src.rock
make -C lgi
make[1]: Entering directory '/tmp/luarocks_lgi-0.9.2-1-uTlnKj/lgi/lgi'
pkg-config --exists 'gobject-introspection-1.0 >= 0.10.8' --print-errors
touch .depcheck
gcc -fPIC  -O2 -fPIC -I/usr/include/lua5.1 -pthread -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wall -Wextra -O2 -g -c -o buffer.o buffer.c
In file included from buffer.c:12:
lgi.h:11:10: fatal error: lua.h: No such file or directory
   11 | #include <lua.h>
      |          ^~~~~~~
compilation terminated.
make[1]: *** [Makefile:63: buffer.o] Error 1
make[1]: Leaving directory '/tmp/luarocks_lgi-0.9.2-1-uTlnKj/lgi/lgi'
make: *** [Makefile:16: all] Error 2

Error: Build error: Failed building.
```

**Comment by psychon** [comment]
> -I/usr/include/lua5.1 

Why is there no `lua.h` in your `/usr/include/lua5.1`?

**Comment by nextkitt** [comment]
You can create a config file of luarocks, like this:

```shell
$ cat /$HOME/.luarocks/config.lua 
-- LuaRocks configuration

rocks_trees = {
    { name = "user", root = home .. "/.luarocks" };
    { name = "system", root = "/usr/local" };
}
lua_interpreter = "lua";
variables = {
    LUA_DIR = "/";
    LUA_INCDIR = "YOUR LUA INCLUDE PATH";
    LUA_BINDIR = "/bin";
    LUA_LIBDIR = "YOUR LUA LIBRARY PATH";
}
