### ISSUE TITLE
Help: translating Python program using gi to Lua with signals

### ISSUE THREAD

**Issue by doronbehar** [pavouk/lgi#221]
Hey guys,

I would like to write a Lua script that would do the equivalent of [this Python script](https://github.com/acrisci/playerctl/blob/v2.0.1/examples/player-manager.py). After reading the [quick overview](https://github.com/pavouk/lgi/blob/0.9.2/docs/overview.md#quick-overview) and another [example of Lua code doing something similar to what I need](https://github.com/AlterationBrick/awesome-playerctl-widget/blob/5c7ebaf/playerctl.lua), I tried to do this:

```lua
lgi = require('lgi')
manager = lgi.Playerctl.PlayerManager
function manager:name_appeared(player)
    print("player appeared")
end
```

But this gives the following error:

```
stdin:1: Playerctl.PlayerManager: no `name_appeared'
stack traceback:
        [C]: in function 'error'
        /home/doron/.luarocks/share/lua/5.3/lgi/component.lua:160: in function </home/doron/.luarocks/share/lua/5.3/lgi/component.lua:156>
        [C]: in metamethod '__newindex'
        stdin:1: in main chunk
        [C]: in ?
```
I can't figure out why this error appears. It means that there is no such signal named `name_appeared` bindable in the object right? If so, how come the Python code which uses Python's `manager.connect` works? I must have done something wrong.

The official language agnostic documentation for `lgi.Playerctl.PlayerManager` is located [here](https://dubstepdish.com/playerctl/PlayerctlPlayerManager.html).

I'd very much appreciate any help, please. Thanks in advance.

**Comment by psychon** [comment]
> After reading the quick overview and

Well, the quick overview says that you should assign to `on_signalname` to connect to `signalname`, I think. I have to admit that I never really worked with signals and LGI myself.

Basically, I think your code should look like this:
```lua
lgi = require('lgi')
manager = lgi.Playerctl.PlayerManager
function manager:on_name_appeared()
    print("player appeared")
end
```
Actually... It might be that you also need this version since the signal has a minus sign instead of an underscore:
```
manage["on_name-appeared"] = function() print("player appeared") end
```
Finally, I think you need to run a main loop at the end: `require("lgi").GLib.MainLoop():run()`.

Does this work?

**Comment by doronbehar** [comment]
Oh, thank you. I missed `on_` prefix while reading the quick overview. Fortunately, now the error does not appear but I don't get anything printed when a new player appears so that's probably a different problem.
Also I checked and using the `[""]` syntax is not needed for this signal because lgi seems to translate the underscores correctly.

**Comment by psychon** [comment]
Well... here is a quick experiment with Gtk. It opens a window and prints a line whenever I switch to another workspace and then back to the workspace with the window. So... this signal seems to work.
```lua
lgi = require("lgi")
Gtk = lgi.Gtk
w = Gtk.Window()
function w:on_visibility_notify_event()
    print("event")
end
w:show()
Gtk.main()
```
Did you try `require("lgi").GLib.MainLoop():run()` as I suggested above? Besides that, I do not have any suggestions. Sorry.

**Comment by doronbehar** [comment]
I did add `require("lgi").GLib.MainLoop():run()` and I also tried `lgi.GLib.MainLoop():run()` which I suppose should do the same. I suppose I'll try to debug this through the process of simplifying the Python script.
