### ISSUE TITLE
'gtk_widget_class_bind_template_child_full' seems not to work

### ISSUE THREAD

**Issue by M1que4s** [pavouk/lgi#254]
Recently I have been trying to work with subclasses and XML templates. So I started with something simple and had the following code:

```lua
-- "Hdy" is from libhandy
App:class("Window", Hdy.ApplicationWindow)

function App.Window:_class_init(klass)
  Gtk.WidgetClass.set_template_from_resource(
    klass,
    "/com/github/M1que4s/App/Templates/Window.ui"
  )

  Gtk.WidgetClass.bind_template_child_full(klass, "Box", true, 0)
end
```

That loaded this template:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<interface>

<template class="AppWindow" parent="HdyApplicationWindow">
  <property name="window-position">center</property>
  <property name="default-width">900</property>
  <property name="default-height">500</property>
  <property name="gravity">center</property>

  <child>
    <!-- Here is the widget that I want to use -->
    <object class="GtkBox" id="Box">
      <property name="visible">True</property>
      <property name="orientation">vertical</property>

      <!-- Some other things that I think isn't necessary to mention -->

    </object>
  </child>

</template>

</interface>
```

It is assumed, that the child widget `Box` should now be part of the widget I am creating and be able to use it somehow in the `_init` function (either by means of `self.priv.Box` or `self.child.Box` or another form).

However, that doesn't happen, it just seems that nothing happens and I can't use that widget. So, what's going on? What can I do about it? What is the actual capacity of the subclasses in LGI?

**The temporary solution I found for this is to create the same widget from code directly, without using a template.**

**Comment by psychon** [comment]
> What can I do about it?

Well... https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-class-bind-template-child-full

> Automatically assign an object declared in the class template XML to be set to a location on a freshly built instance’s private data, or alternatively accessible via gtk_widget_get_template_child().

I'd say: try using `gtk_widget_get_template_child()`.

I do not really understand the following sentence, but it seems you can also do... something? with `get_internal_child()`:

> If internal_child is specified, GtkBuildableIface.get_internal_child() will be automatically implemented by the GtkWidget class so there is no need to implement it manually.

Also, the way you are calling it (last argument 0) means that there is no entry in the private data of the object (and I somehow doubt that this could be used with LGI anyway):

> struct_offset | The structure offset into the composite widget’s instance public or private structure where the automated child pointer should be set, or 0 to not assign the pointer.

**Comment by M1que4s** [comment]
> Well... https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-class-bind-template-child-full

It seems that this function (`gtk_widget_class_bind_template_child`) is not available in LGI or any other Gtk library that uses GObject Introspection. I searched for it using a `for` loop iterating on everything the `_resolve` function returns and couldn't find it. In other languages I'm not sure, but it seems to be the same story.

> I'd say: try using `gtk_widget_get_template_child()`.

I also tried to use that function, but it didn't work.

> I do not really understand the following sentence, but it seems you can also do... something? with `get_internal_child()`:

I haven't tried that function, in fact I didn't know about it. Maybe I can be of help. Apparently the internal widget returns with the id `childname` that was assigned to it.

> Also, the way you are calling it (last argument 0) means that there is no entry in the private data of the object (and I somehow doubt that this could be used with LGI anyway):

I'm aware of that, but the problem here is the same as with 'gtk_widget_class_bind_template_child'; even if I wanted to use G_STRUCT_OFFSET or G_PRIVATE_OFFSET (either for the 'struct_offset' argument), they don't seem to be available either.

Maybe I'm doing something wrong, but after asking people who know a lot about Gtk and seeing several examples of subclasses, it seems that this is not the case.

**Comment by psychon** [comment]
Sorry, I'm out of ideas. <details><summary>Here is my non-working attempt (it only prints `nil` and not a widget).</summary>

```lua
local lgi = require("lgi")
local GLib = lgi.GLib
local Gtk = lgi.Gtk

local template1 = [[
<?xml version="1.0" encoding="UTF-8"?>

<interface>

<template class="AppWindow" parent="GtkWidget">
  <property name="window-position">center</property>
  <property name="default-width">900</property>
  <property name="default-height">500</property>
  <property name="gravity">center</property>

  <child>
    <!-- Here is the widget that I want to use -->
    <object class="GtkBox" id="Box">
      <property name="visible">True</property>
      <property name="orientation">vertical</property>

      <!-- Some other things that I think isn't necessary to mention -->

      </child>

    </object>
  </child>

</template>

</interface>
]]
local template2 = [[
<?xml version="1.0" encoding="UTF-8"?>

<interface>
    <!-- Here is the widget that I want to use -->
    <object class="GtkBox" id="Box">
      <property name="visible">True</property>
      <property name="orientation">vertical</property>

      <!-- Some other things that I think isn't necessary to mention -->

      </child>

    </object>
</interface>
]]

local MyApp = lgi.package("myApp")
local class = MyApp:class("AppWindow", Gtk.Widget)

function MyApp.AppWindow:_class_init(klass)
	local bytes = GLib.Bytes.new(template1)
	klass:set_template(bytes)
	klass:bind_template_child_full("Box", true, 0)
end

function MyApp.AppWindow:_init(...)
	print(self:get_template_child(Gtk.Box, "Box"))
end


local widget = MyApp.AppWindow()
print(widget:get_template_child(Gtk.Box, "Box"))
```
</details>

> but after asking people who know a lot about Gtk

If you know people, you could ask them for some hints on how to make this work in a binding-friendly way / without using private data of the widget.

Sorry, I do not have much clue about Gtk-magic.

**Comment by M1que4s** [comment]
> If you know people, you could ask them for some hints on how to make this work in a binding-friendly way / without using private data of the widget.

Yes, but not knowing about the language I'm using and about LGI, it doesn't help me much about this in particular. However, I will continue to research this and if I find a solution, I will post it here.

> Here is my non-working attempt (it only prints nil and not a widget).

Yep, that's what happens

> Sorry, I do not have much clue about Gtk-magic.

I really don't either, but I'm trying to learn.

**In any case, I will continue to investigate this.**

**Comment by psychon** [comment]
Random idea: How would a Python example for this look like? Or any other language with GI bindings that is not C and thus cannot just use the C macros.

**Comment by M1que4s** [comment]
> Random idea: How would a Python example for this look like? Or any other language with GI bindings that is not C and thus cannot just use the C macros.

Sorry for the delay.

It is a good proposal that you mention, I have not looked for similar examples in other languages. I've been busy, but I'll look for something like what you say to see if it's helpful.

**Comment by M1que4s** [comment]
> Random idea: How would a Python example for this look like? Or any other language with GI bindings that is not C and thus cannot just use the C macros.

Okay, I've been looking and asking and... Basically, the templates in GTK were made thinking mainly in Vala and the implementation depends on both the language and the library itself. 

The reason for this is because it is a feature of GTK that uses very specific C tricks or features, such as macros and memory management that is done with the fields in the structs.

Still, an effort is made in the different libraries to be able to support this GTK feature in other languages. Here are some examples of how this looks in different languages:

Javascript:
```js
/* imports... */

var X = GObject.registerClass({
    Template: 'url://templateurl',
    Children: [ 'button' ],
    GTypeName: "Window",
    // And some other things, like InternalChildren (Array)
  }, class X extends Gtk.ApplicationWindow {
    /* implementation */
});
```

Python:
```python
from gi.repository import Gtk

@Gtk.Template(resource_path='/path/to/resource/window.ui')
class Window(Gtk.Window):
  __gtype_name__ = 'Window'
  button = Gtk.Template.Child()

  def __init__(self, **kwargs):
    super().__init__(**kwargs)

  @Gtk.Template.Callback('clicked')
  def on_button_clicked(self, widget):
    pass
```

**Vala does not use GI and is not able to fully implement the template feature, but it is the language with the best support for that**:
```vala
[GtkTemplate (ui = '/path/to/resource/window.ui')]
public class Window : Gtk.Window
{
  [GtkChild]
  private Gtk.Button button;

  [GtkCallback]
  private void on_button_clicked (Gtk.Button button)
  {
    // Do something...
  }
}
```

**Note that in all examples, only in the JS example the bindings automatically implement the child widgets** (specified in the 'Children' array) to the newly created subclass and allow access to them by means of `_'children'`. In both Python and Vala it is necessary to do this manually.

As for the callbacks, I don't know about that yet.

**Comment by psychon** [comment]
Thanks for the pointers!

So... Javascript / GJs. I got fd162a4 and grepped for 'Template' . `NEWS` pointed me to https://gitlab.gnome.org/GNOME/gjs/-/merge_requests/363 and https://bugzilla.gnome.org/show_bug.cgi?id=700347. That lead to  (via `git blame` and going back in history a bit):
- https://gitlab.gnome.org/GNOME/gjs/-/commit/3e28510522d819b2106047580d2742efc0100952
- https://gitlab.gnome.org/GNOME/gjs/-/commit/40ff788fc16fd1f61ddf958289ecfa8c1ffcc011
- https://gitlab.gnome.org/GNOME/gjs/-/commit/5c84dc06e38a5ef4c3b58978e1e1f973b99f0049
- https://gitlab.gnome.org/GNOME/gjs/-/commit/d383df7928441565b06d28c5e5caa4788dc03018

The first commit message is really helpful: 

> [...] and takes care of calling gtk_widget_class_set_template() and gtk_widget_init_template()

We are missing a call to `gtk_widget_init_template()`!

The following patch to https://github.com/pavouk/lgi/issues/254#issuecomment-735386465...
```diff
--- /tmp/t.lua.orig	2020-12-04 15:55:47.336390572 +0100
+++ /tmp/t.lua	2020-12-04 15:56:01.716049278 +0100
@@ -7,11 +7,13 @@ local template1 = [[
 
 <interface>
 
-<template class="AppWindow" parent="GtkWidget">
+<template class="myAppAppWindow" parent="GtkWidget">
+<!--
   <property name="window-position">center</property>
   <property name="default-width">900</property>
   <property name="default-height">500</property>
   <property name="gravity">center</property>
+  -->
 
   <child>
     <!-- Here is the widget that I want to use -->
@@ -21,7 +23,7 @@ local template1 = [[
 
       <!-- Some other things that I think isn't necessary to mention -->
 
-      </child>
+      <!-- </child> -->
 
     </object>
   </child>
@@ -57,6 +59,7 @@ function MyApp.AppWindow:_class_init(kla
 end
 
 function MyApp.AppWindow:_init(...)
+	self:init_template()
 	print(self:get_template_child(Gtk.Box, "Box"))
 end
 
```
...results in:
```
(lua:2705): Gtk-CRITICAL **: 15:56:02.346: gtk_buildable_add_child: assertion 'iface->add_child != NULL' failed
```
At this point I am lost again. I will continue digging a bit.

**Comment by psychon** [comment]
Argh. It was another stupid error. `get_template_child` does not want the expected type as an argument, but the type of `self`:
```lua
local lgi = require("lgi")
local GLib = lgi.GLib
local Gtk = lgi.Gtk

-- Found this template somewhere in the Gtk docs
local template = [[
<?xml version="1.0" encoding="UTF-8"?>
<interface>
  <!-- interface-requires gtk+ 3.8 -->
  <template class="myAppAppWindow" parent="GtkApplicationWindow">
    <property name="title" translatable="yes">Example Application</property>
    <property name="default-width">600</property>
    <property name="default-height">400</property>
    <child>
      <object class="GtkBox" id="content_box">
        <property name="visible">True</property>
        <property name="orientation">vertical</property>
        <child>
          <object class="GtkHeaderBar" id="header">
            <property name="visible">True</property>
            <child type="title">
              <object class="GtkStackSwitcher" id="tabs">
                <property name="visible">True</property>
                <property name="stack">stack</property>
              </object>
            </child>
          </object>
        </child>
        <child>
          <object class="GtkStack" id="stack">
            <property name="visible">True</property>
          </object>
        </child>
      </object>
    </child>
  </template>
</interface>
]]

local MyApp = lgi.package("myApp")
local class = MyApp:class("AppWindow", Gtk.ApplicationWindow)

function MyApp.AppWindow:_class_init(klass)
	local bytes = GLib.Bytes.new(template)
	klass:set_template(bytes)
	klass:bind_template_child_full("content_box", true, 0)
	klass:bind_template_child_full("header", true, 0)
	klass:bind_template_child_full("tabs", true, 0)
end

function MyApp.AppWindow:_init(...)
	self:init_template()
end


local widget = MyApp.AppWindow()
print(widget:get_template_child(MyApp.AppWindow, "content_box"))
print(widget:get_template_child(MyApp.AppWindow, "header"))
print(widget:get_template_child(MyApp.AppWindow, "tabs"))
```
```
lgi.obj 0x5642881f11c0:Gtk.Box(GtkBox)
lgi.obj 0x5642881f2210:Gtk.HeaderBar(GtkHeaderBar)
lgi.obj 0x5642881f3170:Gtk.StackSwitcher(GtkStackSwitcher)
```

**Comment by M1que4s** [comment]
Well, I apologize again for the delay.

Having said that, I agree with you on this, I did not realize that detail or rather I think it was that I did not know how to make proper use of that function.

> Argh. It was another stupid error. `get_template_child` does not want the expected type as an argument, but the type of `self`:

When I tried that function, I thought that the expected type was that of the child widget in question, but when I saw your example I realized that this was not the case.

That's very good, it basically allows a temporary solution like the following:

```lua
-- ...

function MyApp.AppWindow:_init(...)
    self:init_template()
    self.priv.tabs        = self:get_template_child(MyApp.AppWindow, "tabs")
    self.priv.header      = self:get_template_child(MyApp.AppWindow, "header")
    self.priv.content_box = self:get_template_child(MyApp.AppWindow, "content_box")
    print(self.priv.tabs)
    print(self.priv.header)
    print(self.priv.content_box)
end

local widget = MyApp.AppWindow()
print(widget.priv.tabs)
print(widget.priv.header)
print(widget.priv.content_box)
```

Output:

```
lgi.obj 0x55e416c4d170:Gtk.StackSwitcher(GtkStackSwitcher)
lgi.obj 0x55e416ab6260:Gtk.HeaderBar(GtkHeaderBar)
lgi.obj 0x55e416a9d170:Gtk.Box(GtkBox)
lgi.obj 0x55e416c4d170:Gtk.StackSwitcher(GtkStackSwitcher)
lgi.obj 0x55e416ab6260:Gtk.HeaderBar(GtkHeaderBar)
lgi.obj 0x55e416a9d170:Gtk.Box(GtkBox)
```

**Comment by M1que4s** [comment]
I think this can be quite useful and is, in fact, more or less what I was looking for.

**Comment by psychon** [comment]
So... should this issue be closed? (I vaguely remember that you also mentioned some signal connection helper, but I can't find anything, so this is not a "I want less open issues", but rather a honest "is there something else that I can help you with?")

>  it basically allows a temporary solution like the following:

Put differently: Why "temporary"? What's left?

**Comment by M1que4s** [comment]
> So... should this issue be closed? (I vaguely remember that you also mentioned some signal connection helper, but I can't find anything, so this is not a "I want less open issues", but rather a honest "is there something else that I can help you with?")

Sincerely, thank you for your help. 

> Put differently: Why "temporary"? What's left?

As you mentioned, there's also that thing about signals, that basically (apparently) you can link signals to an object or property in a custom class, however, I'm not really sure how that actually works and I haven't tried it either, so I don't really take it too seriously.

However, I was saying it mainly because I think a better solution would be that in LGI this is done automatically as it is in the case of JS. Still, that could also be considered as an optional feature of LGI, so, if you wish, this issue can be closed without problems

And again, thank you very much for your help :)
