### ISSUE TITLE
Flatpak using Gnome 41 runtime fails with Lgi

### ISSUE THREAD

**Issue by rolandlo** [pavouk/lgi#274]
The Xournal++ [flatpak](https://flathub.org/apps/details/com.github.xournalpp.xournalpp), see also [github repo](https://github.com/flathub/com.github.xournalpp.xournalpp/), has worked fine with Lua lgi using the Gnome 3.38 runtime and lgi commit 0fdcf8c677094d0c109dfb199031fdbc0c9c47ea. We use `lgi` for some plugins, in particular a plugin to migrate font sizes from Xournal++ version 1.0.x to version 1.1.0. 
After updating to lgi commit 4071f902b635d3a7078c65162fce347367b1371d and using Gnome 41 runtime, that plugin does not work any longer. Other Lua plugins (that do not use `lgi`) still work.

The error messages  I got (reproduced by another developer) are:

```
(xournalpp:2): GLib-GObject-CRITICAL **: 20:47:46.199: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed

(xournalpp:2): GLib-CRITICAL **: 20:47:46.199: g_once_init_leave: assertion 'result != 0' failed

(xournalpp:2): GLib-GObject-CRITICAL **: 20:47:46.199: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed

(xournalpp:2): GLib-CRITICAL **: 20:47:46.199: g_once_init_leave: assertion 'result != 0' failed

(xournalpp:2): Gtk-ERROR **: 20:47:46.200: GTK 2/3 symbols detected. Using GTK 2/3 and GTK 4 in the same process is not supported
```

Is there a fix for that problem? For further information see [this discussion](https://github.com/flathub/com.github.xournalpp.xournalpp/pull/29#issuecomment-928197050). 

CC @psychon

**Comment by psychon** [comment]
> Is there a fix for that problem?

Well... I never saw that error message before. Which piece of code is loading GTK 3 and which piece is loading GTK 4? Did one of them recently-ish upgrade? I tried to find some Lua code, but "that repo" does not contain the code, just flatpack-things.

A random guess would be: You are doing `require("lgi").Gtk`. This loads the latest version of `Gtk` that is available. If I understood your discussion link correctly, previously there was just Gtk 3 available, but not there is Gtk 4. Thus, this now loads Gtk 4. You want `require("lgi").require("Gtk", "3.0")` instead (no idea if it really is `3.0` that you want nor do I really know the meaning of this string. This is just taken from some code of out of lgi's `samples/` that `git grep found.)

**Comment by rolandlo** [comment]
@psychon Thanks a lot. Indeed this simple change in the Lua plugin fixes the problem.

**Comment by psychon** [comment]
Thanks for the feedback. I'm glad my random guess was right.
