### ISSUE TITLE
Has this been abandoned? For me on v5.3 it doesn't work

### ISSUE THREAD

**Issue by jradxl** [pavouk/lgi#276]
Has this been abandoned? For me on v5.3 it doesn't work
I rolled back my Ubuntu 21.10 system to include 5.3 and luarocks from the Ubuntu archives.
But it does not install via Luarocks, provideing the lua_resume error that others have reported for 5.4
It does build using the git clone and the Makefile, but none of the tests run.
In fact there's no info on how to run the tests! 
I've no idea what the first line in test.lua is trying to achieve
ie. Line 107, local testpath = arg[0]:sub(1, arg[0]:find('[^%/\\]+$') - 1):gsub('[/\\]$', '')
but if I code round it, tests are coded for lgi.so, whereas lgi/corelgilua51.so has been built
And the Makefile in tests creates libregress.so but I don't know what for.

I assume it's me got it wrong
Can you help?

**Comment by Elv13** [comment]
It doesn't support Lua 5.4 well, but it works fine with 5.3 and below. I have seen some bug report in AwesomeWM (which uses LGI) which were *somehow* built with Lua 5.4, but I am *really* not sure how they did it to the point they were capable of running AwesomeWM on Lua 5.4.

As for your install, I suspect something is messing up your Lua environment. Some frameworks or apps, like Lua Torch, are known to causes this type of problem. Can you reproduce the problem from a Docker container?

**Comment by jradxl** [comment]
Thanks for your update.
I've installed a brand new Ubuntu Mate 21.10, and installed the packages from their repositories.
IE Luarocks, which requires lua 5.1
Trying to build shows a lack of gobject-introspection-1.0

Installing 
gobject-introspection//impish,now 1.68.0-1build2 amd64 [installed]
Still doesn't build

root@u2110a:~# luarocks install lgi
Installing https://luarocks.org/lgi-0.9.2-1.src.rock
make -C lgi
make[1]: Entering directory '/tmp/luarocks_lgi-0.9.2-1-ilkXgq/lgi/lgi'
pkg-config --exists 'gobject-introspection-1.0 >= 0.10.8' --print-errors
Package gobject-introspection-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-introspection-1.0' found
make[1]: *** [Makefile:53: .depcheck] Error 1
make[1]: Leaving directory '/tmp/luarocks_lgi-0.9.2-1-ilkXgq/lgi/lgi'
make: *** [Makefile:16: all] Error 2

Error: Build error: Failed building.

So clearly Ubuntu has moved on, without lgi keeping up

**Comment by Elv13** [comment]
Did you do `sudo apt build-dev lua-lgi`?

**Comment by jradxl** [comment]
sudo apt build-dep lua-lgi
I hadn't
Thank you luarocks now installs lgi, using 5.1
With a bit of effort, I now have lgi-git building using 5.1
but the tests sort of run
there is a lot of
```
gireg   :  1:type_boolean                       FAIL
             /usr/local/share/lua/5.1/lgi/namespace.lua:158: Typelib file for namespace 'Regress' (any version) not found
```
Please can you tell me what I do with `libregress.so` and how I should run the tests
Thanks

**Comment by psychon** [comment]
How are you running the tests? The "right way" is `make check`. This builds some regression-testing library from gobject-introspection-1.0 called `Regress`. This library is then used to test some corner cases in the FFI.

Personally, I patch `lgi/Makefile` to add `lua5.3` to `GINAME` and change `-llua` to `-llua5.3` in `LUA_LIB`. Same for `tests/Makefile`, where I additionally change `LUA = lua` to `lua5.3`. With these changes, things "just" work on my Debian Testing system.

**Comment by psychon** [comment]
Closing as "reporter vanished".
