### ISSUE TITLE
Segfault when inserting into a GTree 

### ISSUE THREAD

**Issue by craigbarnes** [pavouk/lgi#53]
The following code causes a segfault in LGI 0.7.1 on Fedora 18:

```
local lgi = require "lgi"
local tree = lgi.GLib.Tree()
tree:insert("key", "val")
```

I'm not sure if this is a sane thing to do, since I was just playing around with the API with no particular purpose. Causing a segfault didn't seem right though, so I just thought I'd report it here.

**Comment by craigbarnes** [comment]
Causing a segfault from Lua side is never acceptable, regardless of whether the code makes sense or not. This still happens in the latest lgi.

**Comment by psychon** [comment]
> Causing a segfault from Lua side is never acceptable, regardless of whether the code makes sense or not. This still happens in the latest lgi.

As far as I know, the following is known by the Lua authors and is not considered to be a bug:
```
$ lua -v  
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
$ lua -e 'debug.getinfo(2).func()'
[1]    17609 segmentation fault (core dumped)  lua -e 'debug.getinfo(2).func()'
```

**Comment by craigbarnes** [comment]
I'm pretty sure the Lua authors consider all Lua-side segfaults bugs *unless* they depend on the `debug` library. The debug library is an exception for obvious reasons.
