### ISSUE TITLE
GByteArray Help?

### ISSUE THREAD

**Issue by daurnimator** [pavouk/lgi#75]
I'm trying to use [GMime.StreamMem](https://developer.gnome.org/gmime/stable/GMimeStreamMem.html), but appear to be getting incorrect behaviour

This code prints out between 0 and 3 bytes of garbage memory to the screen:

``` lua
local out = GMime.StreamMem.new()
out:get_byte_array()
print(out)
```

**Comment by psychon** [comment]
I might be about three years late, but I cannot reproduce:
```
lua -e 'out = require("lgi").GMime.StreamMem.new() print(out, out:get_byte_array())'       
lgi.obj 0x56102d46be80:GMime.StreamMem(GMimeStreamMem)	nil
```
I guess that returning `nil` initially is the intended behaviour, because of the following:
```
lua -e 'out = require("lgi").GMime.StreamMem.new_with_buffer("ab", 2) print(out, out:get_byte_array())'          
lgi.obj 0x559799d1f0a0:GMime.StreamMem(GMimeStreamMem)	ab
```
Can this issue be closed?

**Comment by daurnimator** [comment]
Indeed, I'm not longer able to replicate.
