### ISSUE TITLE
Cannot load cairo in tr_TR.UTF8 locale

### ISSUE THREAD

**Issue by psychon** [pavouk/lgi#97]
This fails for me: (if you have a turkish locale installed. I didn't and first had to edit `/etc/locale.gen` and rerun `locale-gen` to get one.)

    $ lua -e 'print(os.setlocale("tr_TR.UTF8")) ; print(require("lgi").cairo)' 
    tr_TR.UTF8
    lua: /usr/share/lua/5.1/lgi/override/cairo.lua:673: assertion failed!
    stack traceback:
        [C]: in function 'assert'
        /usr/share/lua/5.1/lgi/override/cairo.lua:673: in main chunk
        [C]: in function 'require'
        /usr/share/lua/5.1/lgi/namespace.lua:176: in function </usr/share/lua/5.1/lgi/namespace.lua:148>
        (tail call): ?
        (command line):1: in main chunk
        [C]: ?

It fails looking up a C function. I added a `print(name, method_name, method_info.cname or (cprefix .. method_name))` before this. Output right before the failure is `ImageSurface	get_width	cairo_Image_surface_get_width`.
With this, I came up with the following that demonstrates the problem:

    $ lua -e 'function f() s = "I" ; return s:lower() end ; print(os.setlocale("")) ; print(f()) ; print(os.setlocale("tr_TR.UTF8")) ; print(f()) '
    de_DE.UTF-8
    i
    tr_TR.UTF8
    I

So for some reason, `("I"):tolower()` doesn't produce "i" in a turkish locale.

Sadly, I do not have any suggestions for a fix.

This was originally reported here: https://github.com/awesomeWM/awesome/issues/75

**Comment by psychon** [comment]
I just found `lgi.GLib.utf8_strdown` and thought "that function could be used to fix this...".

**Comment by pavouk** [comment]
The fact that there is no portable way to turn off stupid locale-sensitivity for basic string functions in LUa is just killing me.  I'll try to come up with something, although it will mean slight uglification of code and worse, it might cause some slowdowns (calling lgi GLib method through dynamic lgi binding will definitely be slower than standard Lua string.tolower).

**Comment by pavouk** [comment]
g_utf8_strdown docs:  The exact manner that this is done depends on the current locale, and may result in the number of characters in the string changing.

I'm afraid that this function will have the same problems as standard Lua string.tolower

g_ascii_strdown might be a better candidate to solve this.

**Comment by pavouk** [comment]
Threw in a few ugly hacks.  Unfortunately, at some places it is too early to be able to use GLib.ascii_strdown, so there are hardcoded gsub('I', 'i') statements.  Looking back at the change, maybe it would be more consistent to export core.strdown() and core.strup() implemented in C (using g_ascii_strdown/g_ascii_strup)...

**Comment by pavouk** [comment]
After getting some sleep, I reverted the junk done yesterday night and implemented fix the proper way(tm).  Pushed, everything should work now.

**Comment by psychon** [comment]
Thanks a lot!
